### ISSUE TITLE
Update list of migrated Scala 2 macros

### ISSUE THREAD

**Issue by nicolasstucki** [scalacenter/scala-3-migration-guide#10]
At https://github.com/scalacenter/scala-3-migration-guide/blame/master/docs/macros.md#L11.

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk could you add the ones you have ported?

**Comment by adpi2** [comment]
Reformat the list
Sort by alphabetical order
Add available versions

Add words about tasty stability, and what dotty version it was compiled with...

**Comment by adpi2** [comment]
Add quill
