### ISSUE TITLE
Since master has become main, edit button leads to "page not found"

### ISSUE THREAD

**Issue by aholland** [scalacenter/scala-3-migration-guide#162]
The edit button in the documentation. e.g. at https://scalacenter.github.io/scala-3-migration-guide/docs/scala-3-syntax-rewriting.html, navigates to the URL:
https://github.com/scalacenter/scala-3-migration-guide/edit/master/docs/scala-3-syntax-rewrites.md
but it needs to go to:
https://github.com/scalacenter/scala-3-migration-guide/edit/main/docs/scala-3-syntax-rewrites.md
**Workaround:** simply change master to main in the URL

**Comment by adpi2** [comment]
Thanks for reporting!

**Comment by mlachkar** [comment]
It should be fixed now. thanks for reporting it.
