### ISSUE TITLE
Scala 2 overrides a return type to an inferred type; Scala 3 does not

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scala-3-migration-guide#181]
```
scala 2.13.5> class C; class D extends C
scala 2.13.5> class Test { def foo: C = new C }
scala 2.13.5> class Test2 extends Test { override def foo = new D }
scala 2.13.5> (new Test2).foo
val res0: D = D@5d32c1c7
```

whereas in Scala 3 the type of `res0` is `C`

I'm fairly sure this is intended behavior in Scala 3, but I can't seem to find either a ticket, or a migration guide entry about it.

There is a ticket complaining about the Scala 2 behavior: https://github.com/scala/bug/issues/7212

**Comment by adpi2** [comment]
Thanks for reporting!

Do you think this pattern could cause a compiler error when porting a valid piece of Scala 2.13 code to Scala 3?

**Comment by SethTisue** [comment]
Yes, it happened here: https://github.com/scala/scala-parser-combinators/pull/370

**Comment by dwijnand** [comment]
https://github.com/scala/scala-parser-combinators/pull/370 isn't a compiler error, it's a runtime error.  And I still don't really think either compiler's at fault, as it's just some crazy class casting code

```scala
      def apply(in: Input) = {
        /*
         * transformed reader
         */
        val inMem = in.asInstanceOf[PackratReader[Elem]]
```

**Comment by SethTisue** [comment]
>  isn't a compiler error, it's a runtime error

fair. in any case, it's a potential migration concern.
