### ISSUE TITLE
Broken link to Compatibility Reference on front page

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scala-3-migration-guide#186]
<img width="923" alt="Screen Shot 2021-04-14 at 10 50 14 AM" src="https://user-images.githubusercontent.com/161079/114756076-37225800-9d0f-11eb-8b66-6d6ca40d5e55.png">

the link (https://scalacenter.github.io/scala-3-migration-guide/docs/general/compatibility.html) is 404

**Comment by adpi2** [comment]
Fixed thanks!
