### ISSUE TITLE
syntax rewrites page contradicts indentation documenation

### ISSUE THREAD

**Issue by nemoo** [scalacenter/scala-3-migration-guide#209]
I followed the https://scalacenter.github.io/scala-3-migration-guide/docs/tooling/scala-3-syntax-rewrites.html in order to rewrite a scala 2 application to scala 3.

During the migration, an error occured as documented here: https://github.com/lampepfl/dotty/issues/12503
In the discussion of this issue it was suggested to open a ticket in the migration guide, which I am now doing.

Should I repost the contents of the dotty ticket here? 
The gist of it is: I performed the rewrite as documented in the migration guide: First the -rewrite -indent, then the -rewrite -new-syntax. 
That results in the compilation error as discussed in the dotty issue.

The correct approach as documented here https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html suggests that the operation must be done in the **opposite** order.

**Comment by adpi2** [comment]
Thanks for the report!
