### ISSUE TITLE
Unclosed string literal in Early Initializer example

### ISSUE THREAD

**Issue by izharahmd** [scalacenter/scala-3-migration-guide#56]
While trying out the early intializer example, it seems there is an unclosed string literal at [this line ](https://github.com/scalacenter/scala-3-migration-guide/blame/master/incompat-3.0/early-initializer/README.md#L47) because I could not get the code to compile.

Also, earlier in the example we are taking about trait `Bar`, so for the class example it would be helpful if the class `Fizz` extends `Bar`.  Then the complete example can be compiled.

```scala
trait Bar {
  val name: String
  val size: Int = name.size
}

class Fizz private (val name: String) extends Bar {
  def this() = this("Fizz")
}
```

I can send a PR for this.

**Comment by adpi2** [comment]
Good catch! Thank you for the PR!
