### ISSUE TITLE
Add page on compiler options

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scala-3-migration-guide#60]
When migrating a Scala 2 project, it is useful to configure the compiler properly. The compiler pages will be dedicated to this matter.

It will contain a table of all Scala 2 compiler options, their Scala 3 equivalence, NA if missing and all other Scala 3 options.
Each row could be commented if relevant:
- reason why it is removed
- related discussions, issue or PR
- links to other pages of the guide (dotty migration mode, syntax rewrites...)

It can also include a short paragraph to show how to set the compiler options in sbt based on the scala version.

**Comment by SethTisue** [comment]
Unfortunately, on the Scala 2 side the documentation on flags is rather out of date, as per https://github.com/scala/docs.scala-lang/issues/1711
