### ISSUE TITLE
provide migration advice for early initializers

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scala-3-migration-guide#9]
some previous discussion on this: https://github.com/scala/scala/pull/8370

the Scala 2 warning (only emitted under `-Xsource:3`) says:

> warning: early initializers are deprecated; they will be replaced by trait parameters in 3.0, see the migration guide on avoiding var/val in traits

at the time that message was written, no such migration guide existed, but now that this repo exists, I guess we can keep that wording :-)

**Comment by adpi2** [comment]
We now have a table of incompatibilities that comprises the early initializers:
https://scalacenter.github.io/scala-3-migration-guide/docs/incompatibilities/dropped-features.html#early-initializer
